import Navbar from './components/Navbar';
import SlideBar from './components/SlideBar';
import './globals.css'
import { Nunito_Sans } from 'next/font/google'

const nuto = Nunito_Sans({
  weight: '400',
  subsets: ['latin'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={nuto.className}>
        <div className='grid grid-cols-12 px-24 gap-6 mt-12 h-5/6'>
          <div className=' col-span-3 text-center '>
             <SlideBar/>
          </div>
          <div className='col-span-9  rounded-md bg-secondary_background '>
            <Navbar/>
          {children}
          </div>
        </div>
      
        </body>
    </html>
  )
}
